### ISSUE TITLE
Class merging

### ISSUE THREAD

**Issue by Sirse** [BlackJar72/JBGMinefantasyAddon#2]
Maybe better to merge similar herb's classes into one?
https://gist.github.com/Sirse/daea0a1691259311f6947e875034d4f1

But, needed some workaround for ItemFood

**Comment by BlackJar72** [comment]
I replied earlier, but for it didn't show up for some reason.

I've collapsed them down to 3 classes, all of which can now be eaten, though only the ginseng and marshmallow are good food sources.  Ginseng and marshmallow are separate classes to implement IPlantable.

I don't really like changing things like this much without a very good reason.  Redefining classes damages worlds by making previously valid blocks "go poof"; I'd rather not do that.
