### ISSUE TITLE
Config option for teleport-related stuff

### ISSUE THREAD

**Issue by Sirse** [BlackJar72/JBGMinefantasyAddon#3]
Please, add config option for teleport-related stuff (recipes on/off, full on/off)

**Comment by BlackJar72** [comment]
I plan to add configs for most of this stuff -- just haven't gotten around to it yet.  There will be configs soon.

**Comment by BlackJar72** [comment]
I have added a basic config file.  A more advanced one may come later, depending on how far I want to persue this project, which I planned to be small and short-lived).
